In [ ]:
import tensorflow as tf 
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Data/IDMT_full_mfcc_final.csv")

In [ ]:
arr=np.load("/content/drive/MyDrive/Data/features_full_mfcc_final.npy")

In [ ]:
df['vehicle'].value_counts()

None    4071
C       3902
T        268
M        246
Name: vehicle, dtype: int64

In [ ]:
X=arr
y=np.array(df['vehicle'].tolist())
### Label Encoding -> Label Encoder
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
y=to_categorical(labelencoder.fit_transform(y))
### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
print(np.shape(X_train))
print(np.shape(X_test))
print(np.shape(y_train))
print(np.shape(y_test))

(5940, 128, 87)
(2547, 128, 87)
(5940, 4)
(2547, 4)


In [ ]:
from tensorflow.keras import datasets, layers, models,Sequential
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten,Conv3D,MaxPool1D,Conv2D,Conv1D,MaxPool2D
from tensorflow.keras.optimizers import Adam
from sklearn import metrics
from keras.callbacks import ReduceLROnPlateau
from sklearn.metrics import roc_curve,roc_auc_score
import matplotlib.pyplot as plt

In [ ]:
learning_rate_reduction = ReduceLROnPlateau(monitor='accuracy', patience = 2, verbose=1,factor=0.5, min_lr=0.00001)

In [ ]:
nn = models.Sequential([
        layers.Conv1D(input_shape=(128,87),filters=64,kernel_size=3,padding='same', activation='relu'),
        layers.MaxPool1D(pool_size=2),
        layers.Dropout(0.2),
        layers.Conv1D(filters=64,kernel_size=3,padding='same', activation='relu'),
        layers.MaxPool1D(pool_size=2),
        layers.Dropout(0.2),
        layers.Conv1D(filters=32,kernel_size=3,padding='same', activation='relu'),
        layers.MaxPool1D(pool_size=3),
        layers.Dropout(0.2),
        layers.Conv1D(filters=16,kernel_size=3,padding='same', activation='relu'),
        layers.MaxPool1D(pool_size=2),
        layers.Flatten(),
        layers.Dense(1000, activation='relu'),
        layers.Dropout(0.2),
        layers.Dense(500, activation='relu'),
        layers.Dense(100, activation='relu'),
        layers.Dense(4, activation='softmax')    
    ])

In [ ]:
nn.compile(optimizer='Adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
history=nn.fit(X_train, y_train, epochs=30,callbacks = [learning_rate_reduction])

Epoch 1/30
186/186 [==============================] - 15s 11ms/step - loss: 0.6207 - accuracy: 0.8290 - lr: 0.0010
Epoch 2/30
186/186 [==============================] - 1s 5ms/step - loss: 0.2203 - accuracy: 0.9311 - lr: 0.0010
Epoch 3/30
186/186 [==============================] - 1s 5ms/step - loss: 0.1857 - accuracy: 0.9431 - lr: 0.0010
Epoch 4/30
186/186 [==============================] - 1s 5ms/step - loss: 0.1357 - accuracy: 0.9579 - lr: 0.0010
Epoch 5/30
186/186 [==============================] - 1s 6ms/step - loss: 0.1135 - accuracy: 0.9663 - lr: 0.0010
Epoch 6/30
186/186 [==============================] - 1s 5ms/step - loss: 0.1023 - accuracy: 0.9677 - lr: 0.0010
Epoch 7/30
186/186 [==============================] - 1s 5ms/step - loss: 0.0914 - accuracy: 0.9731 - lr: 0.0010
Epoch 8/30
186/186 [==============================] - 1s 5ms/step - loss: 0.0965 - accuracy: 0.9694 - lr: 0.0010
Epoch 9/30
186/186 [==============================] - 1s 5ms/step - loss: 0.0818 - accuracy: 0

In [ ]:
print("Accuracy of the model on Training Data is - " , nn.evaluate(X_train,y_train)[1]*100 , "%")
print("Accuracy of the model on Testing Data is - " , nn.evaluate(X_test,y_test)[1]*100 , "%")

186/186 [==============================] - 1s 4ms/step - loss: 0.0198 - accuracy: 0.9924
Accuracy of the model on Training Data is -  99.24242496490479 %
80/80 [==============================] - 1s 7ms/step - loss: 0.0343 - accuracy: 0.9894
Accuracy of the model on Testing Data is -  98.93993139266968 %


In [ ]:
import sklearn.metrics as skm

# y_predict=nn.predict(X_test)
y_predict=(nn.predict(X_test) > 0.5).astype("int32")
print(y_predict[0:2])
y_true=y_test
print(y_true)

# res = tf.math.confusion_matrix(y_true,y_predict)
cm = skm.multilabel_confusion_matrix(y_true, y_predict)
print(cm)
print( skm.classification_report(y_true,y_predict))

[[0 0 1 0]
 [0 0 1 0]]
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 ...
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[[1368   14]
  [  11 1154]]

 [[2475    0]
  [   2   70]]

 [[1312    7]
  [   5 1223]]

 [[2461    4]
  [   9   73]]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1165
           1       1.00      0.97      0.99        72
           2       0.99      1.00      1.00      1228
           3       0.95      0.89      0.92        82

   micro avg       0.99      0.99      0.99      2547
   macro avg       0.98      0.96      0.97      2547
weighted avg       0.99      0.99      0.99      2547
 samples avg       0.99      0.99      0.99      2547



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
